### ISSUE TITLE
Finish up Serverconnections.cs

### ISSUE THREAD

**Issue by jasmine-bae** [immersive-command-system/ImmersiveDroneInterface_2#154]
TODO:
- [x] Create one API Endpoint connection with ServerConnection.cs

- [x]  Implement AddDrone

- [x]  Implement AddDroneCallback()

- WAITING ON SERVER TEAM -

- [x] Define new message types for all methods + callbacks

- [ ] Test AddDrone Functionality
