### ISSUE TITLE
Updating New Logic on VRSide for all Server-Based Connections

### ISSUE THREAD

**Issue by jasmine-bae** [immersive-command-system/ImmersiveDroneInterface_2#156]
i.e. depreciating all the ROS Connections and subscribers on Unity and making it work w/o it

_Droneproperties.cs_

- [x] Get rid of rosdroneconnection (more issues following :) )
*note: SERVERSIDE should keep state of the drone rather than in here

_Dronemenu.cs_

- [ ] Initialize menu without rosdroneconnection interfaces or ros connections in general 
- [ ] For getting lat/long/gps position/other drone menu items: we connect to ROStopic directly for these items.
- [ ] Might need to be connected in serverconnections.cs
- note* can be done easily (set it up that way), just needs to figure out how to get information about the drone normally found in rosdroneconnectioninterfaces, which are "hasauthority" and other state variables.

_Waypoint.cs_

- [x] Reference drone should be updated to drone_v2 but it might break stuff (i.e. when its called to super-class)
- [x] mydrone is currently casted to Drone_v2 to hold off from breaking stuff
- used add operator -> needs to be downcasted. If not, it will cause a whole issue where Drone has parameters and attributes that Drone_v2 does not have (i.e. the addwaypoint and other waypoint functions in Drone might be set to some variables/hold info that creating a new Drone_v2 might lose) (Eric said this should work)
- [x] test new waypoint functions/everything changed in VR @PeruDayani 

_WaypointProperties.cs_

- [x] Reference drone should be updated to drone_v2 but it might break stuff (i.e. when its called to super-class)

_*note: drone subscribers is a whole 'nother issue_
_Drone.cs_
- [ ] sensor subscribers
